[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "asyncio>=3.4.3",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "joblib>=1.4.2",
    "openpyxl==3.1.5",
]
